### ISSUE TITLE
[1주차/01] 오목 문제의 시간복잡도가 이렇게 되는게 맞을까요?

### ISSUE THREAD

**Issue by JANG-WON-JUN** [KKS-Algorithm-Study/AlgoRepo#1]
1) 바둑판의 넓이는 정해져 있고, 각 1개의 점마다 4방향의 탐색을 한다. (19 * 19만큼 무조건 탐색함)
2) 따라서 최악의 경우는 모든 바둑판에 검, 흰 바둑돌이 1번씩 번갈아가며 놓인 경우이다.
3) 그 때의 시간 복잡도는 19 * 19 * 4 이므로 상수 시간 복잡도를 가진다

근데 알고리즘 문제에서 상수 시간 복잡도 가진다고 하니 뭔가 읭 스럽네요

**Comment by TaemHam** [comment]
이게 다른 문제들은 입력값 제한 크기가 N이나 M 같은 걸로 주어지는데, 오목 문제는 그게 없어서 헷갈리는 거 같긴 해요
big-O 표기법에는 상수항은 제거한다는 규칙이 있어서, (19 * 19 * 4) 면 전부 제거하니까 그럼 big-O 표기법으로 O(1)인가 싶은지 싶은거죠

이게 정답이다! 라고 할순 없겠지만, 저는 이렇게 생각해요
다른 2차원 배열 탐색 문제들에서 "모든 칸을 탐색한다" 하면 N*M 으로 표기하듯이, 
이 것도 N=19, M=19로 고정된 상태다 뿐이지, 결국 모든 칸을 탐색하려면 N*M 이니까
저는 O(N*M) 이나 O(N**2) 으로 표기할 거 같아요.
