### ISSUE TITLE
[1주차/03] 배열돌리기4의 시간복잡도 계산이 헷갈리는데요..

### ISSUE THREAD

**Issue by JANG-WON-JUN** [KKS-Algorithm-Study/AlgoRepo#2]
1. 쿼리의 갯수를 가지고 순열로 경우의 수를 만드는 갯수 -> kPk
2. 매번 rotate를 돌면서 최소값을 찾는 시간 -> N * M

따라서 알고리즘의 시간 복잡도는 kPk * O(N * M) 로 계산했는데 맞나요..?

**Comment by TaemHam** [comment]
저도 원준님이랑 같은 방식으로 O(kPk * N ** 2)으로 계산했어요
