### ISSUE TITLE
[2주차/05 마법사 상어와 파이어스톰] 2차원 행렬을 1차원 배열로 바꾸는 방법에 대해 궁금한 점이 있습니다.

### ISSUE THREAD

**Issue by JANG-WON-JUN** [KKS-Algorithm-Study/AlgoRepo#4]
2차원 행렬을 1차원 배열로 나타낸 후 문제를 풀 때 궁금한 점이 생겼습니다.

incorrect_matrix = [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]
]

incorrect_arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]

위와 같이 matrix의 행들을 일자로 연결해버리면 그래프 탐색 시 2차원 행렬의 "벽"을 나타낼 수 없기에 다음과 같이 나타내야 된다고 배웠습니다.

마치 2차원 행렬에 벽이 있는 것 같이 한 겹을 더 감싸고 그것을 1차원 배열로 나타내는 것이죠
correct_matrix = [
 [1, 2, 3, 0],
 [4, 5, 6, 0],
 [7, 8, 9, 0],
 [0, 0, 0, 0]
]

correct_arr = [1, 2, 3, 0, 4, 5, 6, 0, 7, 8, 9, 0, 0, 0, 0, 0]

=========================================
그런데 마법사 상어와 파이어스톰 문제에서 저는 1차원 배열을 나타날 때 

my_matrix = [
 [1, 2, 3, 0],
 [4, 5, 6, 0],
 [7, 8, 9, 0]
]

my_arr = [1, 2, 3, 0, 4, 5, 6, 0, 7, 8, 9, 0]

이렇게 matrix의 맨 끝 열에만 "벽"을 표현하는 컬럼을 추가했음에도 정답이 나왔습니다.
이 문제에서는 괜찮을 것 같은데, 혹시 correct_matrix[3] 행처럼 [0, 0, .. ,0, 0]인 행을 추가하지 않는다면 다른 문제에서는 틀리는 경우가 있을까요?

왜냐하면 correct_arr 배열의 마지막 0, 0, 0, ..., 0, 0 이 부분은 어떤 문제에서도 필요하지 않을 것 같다는 생각이 들어서요.

**Comment by TaemHam** [comment]
my_arr 처럼 만들어서 푸셨다면 오류가 안나올 수가 없을거에요.
my_arr[9] (숫자 8) 에서 밑에 줄을 확인할 때 my_arr[9 + 4] (없는 인덱스) 에선 `IndexError: list index out of range` 에러가 떠야하거든요.

작성하신 코드를 봤는데, 129 번째줄 if 문 안에 `0 <= nx < len(board)` 이 부분을 넣어놓으셔서 정상 작동 하게 되네요.
만약 my_arr에 `0, 0, 0, ..., 0, 0` 이 부분을 넣어주면, if 문에 위의 부분이 없어도 잘 작동하게 됩니다.
