### ISSUE TITLE
파이썬의 삼항 연산자에 관하여..

### ISSUE THREAD

**Issue by JANG-WON-JUN** [KKS-Algorithm-Study/AlgoRepo#6]
파이썬의 삼항 연산자로 if ~ else 문을 대체할 수 있는 경우가 있습니다.

그러나 삼항 연산자를 사용하였을 때 같은 로직의 속도가 늘어나더라구요.

혹시 알고리즘을 풀 때 삼항 연산자보다 if ~ else 문을 사용하는 것이 바람직 할까요?

[참고링크] : https://stackoverflow.com/questions/44599860/performance-of-ternary-operator-vs-if-else-statement

**Comment by TaemHam** [comment]
일단 제가 생각했을 때 결론은 "아니오" 입니다
알고리즘은 연산을 빠르고 효율적으로 하는 걸 목적으로 하는데요,
이게 낮은 시간 복잡도, 즉 적은 연산 횟수에 의해 빨라지는 게 아니라, 언어의 특정 문법 구현 속도 차이로 빨라지는 거라면
저는 그 방식을 쓰라고 하고 싶지 않아요.
지금이야 그 방식이 더 빠를 수 있는데, 나중에 버전업이 되면서 내부 구동 방식이 바뀌고, 다른 방식이 더 빨라질 수도 있거든요
