### ISSUE TITLE
파이썬의 함수 콜에 관하여..

### ISSUE THREAD

**Issue by JANG-WON-JUN** [KKS-Algorithm-Study/AlgoRepo#7]
안녕하세요..

파이썬으로 알고리즘을 풀다가 발견한 것이 있어 질문 드립니다..

같은 로직이라도 일부 로직을 함수로 추출 후 실행하면 최대 2배까지 빨라지더라구요..

찾아보니 다음과 같은 블로그도 발견했습니다..

[참고링크] : https://www.w3docs.com/snippets/python/why-does-python-code-run-faster-in-a-function.html#:~:text=Python%20code%20can%20run%20faster,directly%20by%20the%20computer's%20CPU.

그렇다면 파이썬에서 같은 로직이라도 함수 추출로 인한 속도의 이점을 살리기 위하여 작성할 수 있는 템플릿 형식이 있을까요...?

**Comment by TaemHam** [comment]
일단 저는 함수를 추출해서 템플릿으로 만들어둔 게 있지는 않습니다... ㅎㅎ

그리고 올려주신 글을 읽어봤는데, 파이썬에서 코드 조각을 함수로 빼면 더 빨라지는 이유가 JIT 컴파일러라고 하는데요,
결론부터 말씀드리자면 일반적으로 사용하는 파이썬은 Python3 인데, 이 파이썬은 JIT 컴파일러를 사용하지 않아요! [[참고](https://velog.io/@ksi2564/%ED%8C%8C%EC%9D%B4%EC%8D%AC%EB%8F%84-JIT-%EC%BB%B4%ED%8C%8C%EC%9D%BC)]

간단히 설명 드리자면 다음과 같습니다:

![image](https://github.com/KKS-Algorithm-Study/AlgoRepo/assets/95671168/dfdaea11-f18b-4682-8023-15faaf793574)

일단 파이썬도 종류가 Cpython(Python3가 여기 속합니다), Pypy 둘로 나뉘는데요, 
Cpython은 인터프리터 언어로, 위 그림처럼 작성된 코드가 컴파일되지 않아요. 그래서 JIT 컴파일러를 사용하지 않습니다. 
반면에 Pypy는 제가 알기론 Cpython을 이용해 Python 으로 작성된 코드를 한 번 컴파일 한 후, 그 컴파일된 코드를 돌리는 것입니다. 이 과정에서 JIT 컴파일러가 사용되고, 그래서 함수화 된 코드들은 최적화가 진행되고, 그래서 조금 더 효율적으로 돌아가는 것 같습니다.
그래서 백준에서도 Python3랑 Pypy 풀이 속도 차이를 보시면, 반복문을 많이 써야하는 문제일수록 Pypy가 효율이 더 좋아지는 걸 볼 수 있을거에요.
